//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskBargainsServices.Client.DataFeedService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataInfo", Namespace="http://schemas.datacontract.org/2004/07/AskBargainsServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONDITIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouponCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForwardLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RebateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowCouponsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TodayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WARRANTYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONDITION {
            get {
                return this.CONDITIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CONDITIONField, value) != true)) {
                    this.CONDITIONField = value;
                    this.RaisePropertyChanged("CONDITION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CouponCode {
            get {
                return this.CouponCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponCodeField, value) != true)) {
                    this.CouponCodeField = value;
                    this.RaisePropertyChanged("CouponCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpireDate {
            get {
                return this.ExpireDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpireDateField, value) != true)) {
                    this.ExpireDateField = value;
                    this.RaisePropertyChanged("ExpireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForwardLink {
            get {
                return this.ForwardLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.ForwardLinkField, value) != true)) {
                    this.ForwardLinkField = value;
                    this.RaisePropertyChanged("ForwardLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgPath {
            get {
                return this.ImgPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgPathField, value) != true)) {
                    this.ImgPathField = value;
                    this.RaisePropertyChanged("ImgPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCategory {
            get {
                return this.ItemCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCategoryField, value) != true)) {
                    this.ItemCategoryField = value;
                    this.RaisePropertyChanged("ItemCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIDField, value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemPriceField, value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalPrice {
            get {
                return this.OriginalPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalPriceField, value) != true)) {
                    this.OriginalPriceField = value;
                    this.RaisePropertyChanged("OriginalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promotion {
            get {
                return this.PromotionField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionField, value) != true)) {
                    this.PromotionField = value;
                    this.RaisePropertyChanged("Promotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishDate {
            get {
                return this.PublishDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishDateField, value) != true)) {
                    this.PublishDateField = value;
                    this.RaisePropertyChanged("PublishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rebate {
            get {
                return this.RebateField;
            }
            set {
                if ((object.ReferenceEquals(this.RebateField, value) != true)) {
                    this.RebateField = value;
                    this.RaisePropertyChanged("Rebate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Save {
            get {
                return this.SaveField;
            }
            set {
                if ((object.ReferenceEquals(this.SaveField, value) != true)) {
                    this.SaveField = value;
                    this.RaisePropertyChanged("Save");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shipping {
            get {
                return this.ShippingField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingField, value) != true)) {
                    this.ShippingField = value;
                    this.RaisePropertyChanged("Shipping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowCoupons {
            get {
                return this.ShowCouponsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowCouponsField, value) != true)) {
                    this.ShowCouponsField = value;
                    this.RaisePropertyChanged("ShowCoupons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Today {
            get {
                return this.TodayField;
            }
            set {
                if ((object.ReferenceEquals(this.TodayField, value) != true)) {
                    this.TodayField = value;
                    this.RaisePropertyChanged("Today");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRated {
            get {
                return this.UserRatedField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRatedField, value) != true)) {
                    this.UserRatedField = value;
                    this.RaisePropertyChanged("UserRated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WARRANTY {
            get {
                return this.WARRANTYField;
            }
            set {
                if ((object.ReferenceEquals(this.WARRANTYField, value) != true)) {
                    this.WARRANTYField = value;
                    this.RaisePropertyChanged("WARRANTY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyInfo", Namespace="http://schemas.datacontract.org/2004/07/AskBargainsServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CompanyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIDField, value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSiteUrl {
            get {
                return this.WebSiteUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteUrlField, value) != true)) {
                    this.WebSiteUrlField = value;
                    this.RaisePropertyChanged("WebSiteUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataFeedService.IDataFeedService")]
    public interface IDataFeedService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetAllFileList", ReplyAction="http://tempuri.org/IDataFeedService/GetAllFileListResponse")]
        string[] GetAllFileList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByFileNameList", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByFileNameListResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByFileNameList(string[] fileNameList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByFileName", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByFileNameResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByFileName(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByDefault", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByDefaultResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByDefault();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByDateString", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByDateStringResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByDateString(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByDate", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByDateResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByNumberOfItems", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByNumberOfItemsResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByNumberOfItems(int numberOfItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetAllDataInfoOrderByDesc", ReplyAction="http://tempuri.org/IDataFeedService/GetAllDataInfoOrderByDescResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetAllDataInfoOrderByDesc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByItemIDList", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByItemIDListResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByItemIDList(string[] itemIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByCompanyID", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByCompanyIDResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByCompanyID(string companyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByCompanyName", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByCompanyNameResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByCompanyName(string companyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoByItemID", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoByItemIDResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo GetDataInfoByItemID(string itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByBrand", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByBrandResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByBrand(string brandName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetDataInfoListByCatagory", ReplyAction="http://tempuri.org/IDataFeedService/GetDataInfoListByCatagoryResponse")]
        AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByCatagory(string catagoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetAllCompanyInfoList", ReplyAction="http://tempuri.org/IDataFeedService/GetAllCompanyInfoListResponse")]
        AskBargainsServices.Client.DataFeedService.CompanyInfo[] GetAllCompanyInfoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetCompanyInfoByCompanyID", ReplyAction="http://tempuri.org/IDataFeedService/GetCompanyInfoByCompanyIDResponse")]
        AskBargainsServices.Client.DataFeedService.CompanyInfo GetCompanyInfoByCompanyID(string companyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataFeedService/GetCompanyInfoByItemID", ReplyAction="http://tempuri.org/IDataFeedService/GetCompanyInfoByItemIDResponse")]
        AskBargainsServices.Client.DataFeedService.CompanyInfo GetCompanyInfoByItemID(string itemID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataFeedServiceChannel : AskBargainsServices.Client.DataFeedService.IDataFeedService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataFeedServiceClient : System.ServiceModel.ClientBase<AskBargainsServices.Client.DataFeedService.IDataFeedService>, AskBargainsServices.Client.DataFeedService.IDataFeedService {
        
        public DataFeedServiceClient() {
        }
        
        public DataFeedServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataFeedServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataFeedServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataFeedServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetAllFileList() {
            return base.Channel.GetAllFileList();
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByFileNameList(string[] fileNameList) {
            return base.Channel.GetDataInfoListByFileNameList(fileNameList);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByFileName(string fileName) {
            return base.Channel.GetDataInfoListByFileName(fileName);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByDefault() {
            return base.Channel.GetDataInfoListByDefault();
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByDateString(string date) {
            return base.Channel.GetDataInfoListByDateString(date);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByDate(System.DateTime date) {
            return base.Channel.GetDataInfoListByDate(date);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByNumberOfItems(int numberOfItems) {
            return base.Channel.GetDataInfoListByNumberOfItems(numberOfItems);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetAllDataInfoOrderByDesc() {
            return base.Channel.GetAllDataInfoOrderByDesc();
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByItemIDList(string[] itemIDList) {
            return base.Channel.GetDataInfoListByItemIDList(itemIDList);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByCompanyID(string companyID) {
            return base.Channel.GetDataInfoListByCompanyID(companyID);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByCompanyName(string companyName) {
            return base.Channel.GetDataInfoListByCompanyName(companyName);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo GetDataInfoByItemID(string itemID) {
            return base.Channel.GetDataInfoByItemID(itemID);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByBrand(string brandName) {
            return base.Channel.GetDataInfoListByBrand(brandName);
        }
        
        public AskBargainsServices.Client.DataFeedService.DataInfo[] GetDataInfoListByCatagory(string catagoryName) {
            return base.Channel.GetDataInfoListByCatagory(catagoryName);
        }
        
        public AskBargainsServices.Client.DataFeedService.CompanyInfo[] GetAllCompanyInfoList() {
            return base.Channel.GetAllCompanyInfoList();
        }
        
        public AskBargainsServices.Client.DataFeedService.CompanyInfo GetCompanyInfoByCompanyID(string companyID) {
            return base.Channel.GetCompanyInfoByCompanyID(companyID);
        }
        
        public AskBargainsServices.Client.DataFeedService.CompanyInfo GetCompanyInfoByItemID(string itemID) {
            return base.Channel.GetCompanyInfoByItemID(itemID);
        }
    }
}
